- hosts: all
  become: true
  tasks:
    - name: Create a new user
      user:
        name: "ubuntu"
        state: present
        shell: /bin/bash
        groups: sudo
        append: yes

    - name: Copy SSH public key to the new user
      authorized_key:
        user: "ubuntu"
        key: "{{ item }}"
      with_file:
        - ~/.ssh/id_rsa.pub
