- hosts: lb
  name: Install Docker
  remote_user: ci
  become: true
  tasks:
    - name: Uninstall all conflicting packages
      apt:
        name: "{{ item }}"
        state: absent
      with_items:
        - docker.io
        - docker-doc
        - docker-compose
        - docker-compose-v2
        - podman-docker
        - containerd
        - runc

    - name: Update system packages using apt
      apt:
        update_cache: yes

    - name: Install required system packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Get architecture
      shell: dpkg --print-architecture
      register: dpkg_architecture

    - name: Get distribution
      shell: lsb_release -cs
      register: lsb_release

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch={{ dpkg_architecture.stdout }}] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable"
        state: present
        filename: docker

    - name: Update system packages using apt
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: true
