# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    LoadBalancerCount = 1
    (1..LoadBalancerCount).each do |i|
        config.vm.define "k8s-lb-#{i}" do |master|
            master.vm.box = "ubuntu-22.04.3"
            master.vm.hostname = "k8s-lb-#{i}"
            master.vm.network "private_network", ip: "172.16.1.1#{i}"
            master.vm.provider "virtualbox" do |vm|
                vm.name = "k8s-lb-#{i}"
                vm.memory = 1024
                vm.cpus = 1
            end
        end
    end

    # MasterCount = 3
    # (1..MasterCount).each do |i|
    #     config.vm.define "k8s-master-#{i}" do |master|
    #         master.vm.box = "ubuntu-22.04.3"
    #         master.vm.hostname = "k8s-master-#{i}"
    #         master.vm.network "private_network", ip: "172.16.2.1#{i}"
    #         master.vm.provider "virtualbox" do |vm|
    #             vm.name = "k8s-master-#{i}"
    #             vm.memory = 1024
    #             vm.cpus = 1
    #         end
    #     end
    # end

    # WorkerCount = 3
    # (1..WorkerCount).each do |i|
    #     config.vm.define "k8s-worker-#{i}" do |worker|
    #         worker.vm.box = "ubuntu-22.04.3"
    #         worker.vm.hostname = "k8s-worker-#{i}"
    #         worker.vm.network "private_network", ip: "172.16.3.1#{i}"
    #         worker.vm.provider "virtualbox" do |vm|
    #             vm.name = "k8s-worker-#{i}"
    #             vm.memory = 1024
    #             vm.cpus = 1
    #         end
    #     end
    # end

    # config.vm.provision "shell", path: "./setup_k8s.sh"
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    config.vm.provision "shell", inline: <<-SHELL
        echo 1
    SHELL
    # config.ssh.private_key_path = "../.ssh/id_ed25519"

end
